//! `Cargo.lock` v3 and v4, byte-compatible with cargo.

use anyhow::{Context, Result, bail};
use semver::Version;
use std::path::Path;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LockDep {
    pub name: String,
    pub version: Option<Version>,
    pub source: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockPkg {
    pub name: String,
    pub version: Version,
    /// None for a path package.
    pub source: Option<String>,
    pub checksum: Option<String>,
    pub dependencies: Vec<LockDep>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Lockfile {
    pub version: u32,
    pub packages: Vec<LockPkg>,
}

fn parse_dep(s: &str) -> Result<LockDep> {
    let mut it = s.splitn(3, ' ');
    let name = it.next().context("empty dependency entry")?.to_owned();
    let version = it
        .next()
        .map(Version::parse)
        .transpose()
        .with_context(|| format!("invalid lockfile dependency `{s}`"))?;
    let source = it.next().map(|s| s.trim_start_matches('(').trim_end_matches(')').to_owned());
    Ok(LockDep { name, version, source })
}

pub fn read(path: &Path) -> Result<Option<Lockfile>> {
    let text = match std::fs::read_to_string(path) {
        Ok(t) => t,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(e).with_context(|| format!("failed to read {}", path.display())),
    };
    let table: toml::Table = toml::from_str(&text).with_context(|| format!("failed to parse {}", path.display()))?;
    let version = table.get("version").and_then(|v| v.as_integer()).unwrap_or(1) as u32;
    if version < 3 {
        bail!(
            "{} uses lockfile format v{version}; rb reads v3 and v4 (regenerate it by deleting the file)",
            path.display()
        );
    }
    let mut packages = Vec::new();
    for p in table.get("package").and_then(|p| p.as_array()).into_iter().flatten() {
        let s = |k: &str| p.get(k).and_then(|v| v.as_str()).map(str::to_owned);
        packages.push(LockPkg {
            name: s("name").context("lockfile package without a name")?,
            version: Version::parse(&s("version").context("lockfile package without a version")?)?,
            source: s("source"),
            checksum: s("checksum"),
            dependencies: p
                .get("dependencies")
                .and_then(|d| d.as_array())
                .into_iter()
                .flatten()
                .filter_map(|d| d.as_str())
                .map(parse_dep)
                .collect::<Result<_>>()?,
        });
    }
    Ok(Some(Lockfile { version, packages }))
}

impl Lockfile {
    /// Sorted. Deps are as short as they can be and still unambiguous: `name`, then version, then source.
    pub fn render(&self) -> String {
        let mut pkgs = self.packages.clone();
        pkgs.sort_by(|a, b| (&a.name, &a.version, &a.source).cmp(&(&b.name, &b.version, &b.source)));
        let count = |name: &str| pkgs.iter().filter(|p| p.name == name).count();
        let versions = |name: &str, v: &Version| pkgs.iter().filter(|p| p.name == name && &p.version == v).count();
        let mut out = String::from("# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\n");
        out.push_str(&format!("version = {}\n", self.version.max(3)));
        for p in &pkgs {
            out.push_str("\n[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", p.name));
            out.push_str(&format!("version = \"{}\"\n", p.version));
            if let Some(s) = &p.source {
                out.push_str(&format!("source = \"{s}\"\n"));
            }
            if let Some(c) = &p.checksum {
                out.push_str(&format!("checksum = \"{c}\"\n"));
            }
            let mut deps: Vec<String> = p
                .dependencies
                .iter()
                .map(|d| {
                    let v = d.version.as_ref();
                    match v {
                        Some(v) if count(&d.name) > 1 => match (&d.source, versions(&d.name, v) > 1) {
                            (Some(s), true) => format!("{} {v} ({s})", d.name),
                            _ => format!("{} {v}", d.name),
                        },
                        _ => d.name.clone(),
                    }
                })
                .collect();
            deps.sort();
            deps.dedup();
            if !deps.is_empty() {
                out.push_str("dependencies = [\n");
                for d in deps {
                    out.push_str(&format!(" \"{d}\",\n"));
                }
                out.push_str("]\n");
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_cargo_format() {
        let text = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\ndependencies = [\n \"itoa\",\n \"syn 1.0.109\",\n \"syn 2.0.1\",\n]\n\n[[package]]\nname = \"itoa\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"abc\"\n\n[[package]]\nname = \"syn\"\nversion = \"1.0.109\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"d1\"\n\n[[package]]\nname = \"syn\"\nversion = \"2.0.1\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"d2\"\n";
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("Cargo.lock");
        std::fs::write(&p, text).unwrap();
        let lock = read(&p).unwrap().unwrap();
        assert_eq!(lock.packages.len(), 4);
        assert_eq!(lock.render(), text);
    }
}
