//! `run`, `test`, `bench`, and `doc` on the offline `testing` fixture

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

struct Project {
    _dir: tempfile::TempDir,
    root: PathBuf,
}

fn copy_dir(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).unwrap();
    for e in std::fs::read_dir(from).unwrap() {
        let e = e.unwrap();
        let dst = to.join(e.file_name());
        if e.file_type().unwrap().is_dir() {
            if e.file_name() != "target" {
                copy_dir(&e.path(), &dst);
            }
        } else {
            std::fs::copy(e.path(), dst).unwrap();
        }
    }
}

impl Project {
    fn testing() -> Self {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().canonicalize().unwrap();
        let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/testing");
        copy_dir(&fixture, &root.join("ws"));
        Self { _dir: dir, root }
    }

    fn ws(&self) -> PathBuf {
        self.root.join("ws")
    }

    fn rb(&self, args: &[&str]) -> Output {
        Command::new(env!("CARGO_BIN_EXE_rb"))
            .arg(args[0])
            .args(["--color", "never"])
            .args(&args[1..])
            .current_dir(self.ws())
            .env("RB_HOME", self.root.join("home"))
            .env("RB_STORE_DIR", self.root.join("store"))
            .env("RB_COMPACT", "sync")
            .env_remove("RUSTC_WRAPPER")
            .output()
            .unwrap()
    }

    /// Runs rb, asserting success; returns stdout + stderr
    fn ok(&self, args: &[&str]) -> String {
        let out = self.rb(args);
        let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
        assert!(out.status.success(), "rb {args:?} failed:\n{text}");
        text
    }
}

#[test]
fn replace_section_uses_the_path_crate() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    let demo = root.join("demo");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::create_dir_all(demo.join("src")).unwrap();
    std::fs::write(
        demo.join("Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"1.0.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(demo.join("src/lib.rs"), "pub fn n() -> i32 { 9 }\n").unwrap();
    std::fs::write(app.join("src/main.rs"), "fn main() { assert_eq!(demo::n(), 9); }\n").unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ndemo = \"=1.0.0\"\n\n[replace]\n\"demo:1.0.0\" = { path = \"../demo\" }\n",
    )
    .unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["build", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
}

#[test]
fn vendor_directory_replaces_crates_io() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    let vendor = app.join("vendor/demo-1.0.0");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::create_dir_all(app.join(".cargo")).unwrap();
    std::fs::create_dir_all(vendor.join("src")).unwrap();
    std::fs::write(app.join("src/main.rs"), "fn main() { assert_eq!(demo::n(), 7); }\n").unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ndemo = \"1.0\"\n",
    )
    .unwrap();
    std::fs::write(
        app.join(".cargo/config.toml"),
        "[source.crates-io]\nreplace-with = \"vendored\"\n\n[source.vendored]\ndirectory = \"vendor\"\n",
    )
    .unwrap();
    std::fs::write(
        vendor.join("Cargo.toml"),
        "[package]\nname = \"demo\"\nversion = \"1.0.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(vendor.join("src/lib.rs"), "pub fn n() -> i32 { 7 }\n").unwrap();
    let sum = "a".repeat(64);
    std::fs::write(
        vendor.join(".cargo-checksum.json"),
        format!(r#"{{"files":{{}},"package":"{sum}"}}"#),
    )
    .unwrap();
    std::fs::write(
        app.join("Cargo.lock"),
        format!(
            r#"# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "app"
version = "0.1.0"
dependencies = ["demo"]

[[package]]
name = "demo"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "{sum}"
"#
        ),
    )
    .unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["build", "--locked", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    assert!(text.contains("Finished"), "{text}");
}

#[test]
fn message_format_short_is_accepted() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"bad\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(root.join("src/lib.rs"), "fn broken( {}\n").unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["build", "--message-format=short", "--offline", "--color", "never"])
        .current_dir(&root)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let stderr = String::from_utf8_lossy(&out.stderr);
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(!out.status.success());
    assert!(!stderr.contains("unknown --message-format"), "{stderr}");
    assert!(stderr.contains("error"), "{stderr}");
    assert!(!stdout.contains("compiler-message"), "{stdout}");
}

#[test]
fn tree_matches_cargo_for_a_path_dep() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    let lib = root.join("lib");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::create_dir_all(lib.join("src")).unwrap();
    std::fs::write(app.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(lib.join("src/lib.rs"), "\n").unwrap();
    std::fs::write(
        lib.join("Cargo.toml"),
        "[package]\nname = \"mylib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nmylib = { path = \"../lib\" }\n",
    )
    .unwrap();
    let cargo = Command::new("cargo")
        .args(["tree", "--offline", "--manifest-path"])
        .arg(app.join("Cargo.toml"))
        .current_dir(&app)
        .output()
        .unwrap();
    if !cargo.status.success() {
        let lock = Command::new("cargo")
            .args(["generate-lockfile"])
            .current_dir(&app)
            .output()
            .unwrap();
        assert!(lock.status.success(), "{}", String::from_utf8_lossy(&lock.stderr));
    }
    let cargo = Command::new("cargo")
        .args(["tree", "--charset", "ascii"])
        .current_dir(&app)
        .output()
        .unwrap();
    let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["tree", "--charset", "ascii", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let cargo_text = String::from_utf8_lossy(&cargo.stdout);
    let rb_text = String::from_utf8_lossy(&rb.stdout);
    assert!(cargo.status.success(), "{}", String::from_utf8_lossy(&cargo.stderr));
    assert!(rb.status.success(), "{}\n{rb_text}", String::from_utf8_lossy(&rb.stderr));
    assert_eq!(rb_text.trim(), cargo_text.trim(), "rb:\n{rb_text}\ncargo:\n{cargo_text}");
    let cargo_none = Command::new("cargo")
        .args(["tree", "--prefix", "none"])
        .current_dir(&app)
        .output()
        .unwrap();
    let rb_none = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["tree", "--prefix", "none", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    assert!(cargo_none.status.success() && rb_none.status.success());
    assert_eq!(
        String::from_utf8_lossy(&rb_none.stdout).trim(),
        String::from_utf8_lossy(&cargo_none.stdout).trim()
    );
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dev-dependencies]\nmylib = { path = \"../lib\" }\n",
    )
    .unwrap();
    let _ = std::fs::remove_file(app.join("Cargo.lock"));
    let normal = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["tree", "--charset", "ascii", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let dev = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["tree", "--edges", "dev", "--charset", "ascii", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let normal_text = String::from_utf8_lossy(&normal.stdout);
    let dev_text = String::from_utf8_lossy(&dev.stdout);
    assert!(normal.status.success() && !normal_text.contains("mylib"), "{normal_text}");
    assert!(
        dev.status.success() && dev_text.contains("mylib"),
        "{dev_text}\n{}",
        String::from_utf8_lossy(&dev.stderr)
    );
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nmylib = { path = \"../lib\" }\n",
    )
    .unwrap();
    let _ = std::fs::remove_file(app.join("Cargo.lock"));
    let cargo_inv = Command::new("cargo")
        .args(["tree", "-i", "mylib", "--prefix", "none"])
        .current_dir(&app)
        .output()
        .unwrap();
    let rb_inv = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["tree", "--invert", "mylib", "--prefix", "none", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    assert!(cargo_inv.status.success(), "{}", String::from_utf8_lossy(&cargo_inv.stderr));
    assert!(rb_inv.status.success(), "{}", String::from_utf8_lossy(&rb_inv.stderr));
    assert_eq!(
        String::from_utf8_lossy(&rb_inv.stdout).trim(),
        String::from_utf8_lossy(&cargo_inv.stdout).trim()
    );
}

#[test]
fn tree_format_matches_cargo() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    let lib = root.join("lib");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::create_dir_all(lib.join("src")).unwrap();
    std::fs::write(app.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(lib.join("src/lib.rs"), "\n").unwrap();
    std::fs::write(
        lib.join("Cargo.toml"),
        "[package]\nname = \"my-lib\"\nversion = \"0.1.0\"\nedition = \"2021\"\nlicense = \"MIT\"\nrepository = \"https://example.com/lib\"\n\n[features]\ndefault = [\"a\"]\na = []\n",
    )
    .unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\nlicense = \"Apache-2.0\"\n\n[dependencies]\nmy-lib = { path = \"../lib\", features = [\"a\"] }\n",
    )
    .unwrap();
    let lock = Command::new("cargo")
        .args(["generate-lockfile"])
        .current_dir(&app)
        .output()
        .unwrap();
    assert!(lock.status.success(), "{}", String::from_utf8_lossy(&lock.stderr));
    for fmt in ["{lib}", "{p} {l} {r}", "{lib} [{f}]"] {
        let cargo = Command::new("cargo")
            .args(["tree", "--charset", "ascii", "--format", fmt])
            .current_dir(&app)
            .output()
            .unwrap();
        let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
            .args(["tree", "--charset", "ascii", "--format", fmt, "--offline", "--color", "never"])
            .current_dir(&app)
            .env("RB_HOME", root.join("home"))
            .env("RB_STORE_DIR", root.join("store"))
            .env("RB_COMPACT", "off")
            .output()
            .unwrap();
        let cargo_text = String::from_utf8_lossy(&cargo.stdout);
        let rb_text = String::from_utf8_lossy(&rb.stdout);
        assert!(cargo.status.success(), "{fmt}: {}", String::from_utf8_lossy(&cargo.stderr));
        assert!(rb.status.success(), "{fmt}: {}\n{rb_text}", String::from_utf8_lossy(&rb.stderr));
        assert_eq!(
            rb_text.trim(),
            cargo_text.trim(),
            "format {fmt}\nrb:\n{rb_text}\ncargo:\n{cargo_text}"
        );
    }
    let bad = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["tree", "--format", "{nope}", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    assert!(!bad.status.success());
    let err = String::from_utf8_lossy(&bad.stderr);
    assert!(err.contains("unsupported pattern `nope`"), "{err}");
}

#[test]
fn pkgid_matches_cargo() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let manifest = root.join("ws/Cargo.toml");
    let lock = Command::new("cargo")
        .args(["generate-lockfile", "--manifest-path"])
        .arg(&manifest)
        .output()
        .unwrap();
    assert!(lock.status.success(), "{}", String::from_utf8_lossy(&lock.stderr));
    let cargo = Command::new("cargo")
        .args(["pkgid", "--offline", "--locked", "--manifest-path"])
        .arg(&manifest)
        .output()
        .unwrap();
    let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["pkgid", "--offline", "--locked", "--manifest-path"])
        .arg(&manifest)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let cargo_id = String::from_utf8_lossy(&cargo.stdout).trim().to_owned();
    let rb_id = String::from_utf8_lossy(&rb.stdout).trim().to_owned();
    assert!(cargo.status.success(), "{}", String::from_utf8_lossy(&cargo.stderr));
    assert!(rb.status.success(), "{}", String::from_utf8_lossy(&rb.stderr));
    assert_eq!(rb_id, cargo_id, "rb `{rb_id}` cargo `{cargo_id}`");
}

#[test]
fn fetch_offline_on_a_path_package() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["fetch", "--offline", "--color", "never"])
        .current_dir(root.join("ws"))
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    assert!(text.contains("Fetched"), "{text}");
}

#[test]
fn metadata_resolve_lists_deps() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::create_dir_all(root.join("lib/src")).unwrap();
    std::fs::write(
        root.join("lib/Cargo.toml"),
        "[package]\nname = \"mylib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(root.join("lib/src/lib.rs"), "\n").unwrap();
    std::fs::write(app.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nmylib = { path = \"../lib\" }\n",
    )
    .unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["metadata", "--format-version", "1", "--offline"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let doc: serde_json::Value = serde_json::from_str(&text).unwrap();
    let nodes = doc["resolve"]["nodes"].as_array().unwrap();
    let app_node = nodes.iter().find(|n| n["id"].as_str().unwrap_or("").contains("app")).unwrap();
    let names: Vec<_> = app_node["deps"]
        .as_array()
        .unwrap()
        .iter()
        .map(|d| d["name"].as_str().unwrap().to_owned())
        .collect();
    assert!(names.iter().any(|n| n == "mylib"), "{names:?}");
    assert!(app_node["deps"][0]["dep_kinds"][0]["kind"].is_null());
}

#[test]
fn metadata_features_match_cargo() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::create_dir_all(root.join("lib/src")).unwrap();
    std::fs::write(
        root.join("lib/Cargo.toml"),
        "[package]\nname = \"mylib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[features]\ndefault = [\"a\"]\na = []\n",
    )
    .unwrap();
    std::fs::write(root.join("lib/src/lib.rs"), "\n").unwrap();
    std::fs::write(app.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nmylib = { path = \"../lib\", features = [\"a\"] }\n",
    )
    .unwrap();
    let lock = Command::new("cargo")
        .args(["generate-lockfile"])
        .current_dir(&app)
        .output()
        .unwrap();
    assert!(lock.status.success(), "{}", String::from_utf8_lossy(&lock.stderr));
    let cargo = Command::new("cargo")
        .args(["metadata", "--format-version", "1", "--offline"])
        .current_dir(&app)
        .output()
        .unwrap();
    let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["metadata", "--format-version", "1", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    assert!(cargo.status.success(), "{}", String::from_utf8_lossy(&cargo.stderr));
    assert!(rb.status.success(), "{}", String::from_utf8_lossy(&rb.stderr));
    let c: serde_json::Value = serde_json::from_str(&String::from_utf8_lossy(&cargo.stdout)).unwrap();
    let r: serde_json::Value = serde_json::from_str(&String::from_utf8_lossy(&rb.stdout)).unwrap();
    let feats = |doc: &serde_json::Value, name: &str| -> Vec<String> {
        doc["resolve"]["nodes"]
            .as_array()
            .unwrap()
            .iter()
            .find(|n| n["id"].as_str().unwrap_or("").contains(name))
            .unwrap()["features"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_owned())
            .collect()
    };
    assert_eq!(feats(&r, "mylib"), feats(&c, "mylib"));
    assert_eq!(feats(&r, "app"), feats(&c, "app"));
}

#[test]
fn metadata_matches_cargo_on_hello() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let manifest = root.join("ws/Cargo.toml");
    let cargo = Command::new("cargo")
        .args(["metadata", "--format-version", "1", "--no-deps", "--offline", "--manifest-path"])
        .arg(&manifest)
        .output()
        .unwrap();
    let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["metadata", "--format-version", "1", "--no-deps", "--offline", "--manifest-path"])
        .arg(&manifest)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let cargo_text = String::from_utf8_lossy(&cargo.stdout);
    let rb_text = String::from_utf8_lossy(&rb.stdout);
    assert!(cargo.status.success(), "{}", String::from_utf8_lossy(&cargo.stderr));
    assert!(rb.status.success(), "{}\n{rb_text}", String::from_utf8_lossy(&rb.stderr));
    let c: serde_json::Value = serde_json::from_str(&cargo_text).unwrap();
    let r: serde_json::Value = serde_json::from_str(&rb_text).unwrap();
    assert_eq!(r["version"], 1);
    assert!(r["resolve"].is_null());
    assert_eq!(r["packages"][0]["name"], c["packages"][0]["name"]);
    assert_eq!(r["packages"][0]["version"], c["packages"][0]["version"]);
    assert_eq!(r["packages"][0]["targets"][0]["name"], "hello-world");
    assert_eq!(r["packages"][0]["targets"][0]["kind"], c["packages"][0]["targets"][0]["kind"]);
    assert_eq!(r["workspace_members"].as_array().unwrap().len(), 1);
    assert!(
        r["workspace_members"][0].as_str().unwrap().contains("hello@0.1.0")
            || r["workspace_members"][0].as_str().unwrap().ends_with("#0.1.0")
    );
}

#[test]
fn keep_going_still_builds_independent_packages() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let ws = root.join("ws");
    for (name, src) in [("bad", "fn broken( {\n"), ("good", "pub fn ok() {}\n")] {
        let p = ws.join(name);
        std::fs::create_dir_all(p.join("src")).unwrap();
        std::fs::write(
            p.join("Cargo.toml"),
            format!("[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n"),
        )
        .unwrap();
        let mut body = src.to_owned();
        if name == "bad" {
            body.push_str(&"// pad\n".repeat(4000));
        }
        std::fs::write(p.join("src/lib.rs"), body).unwrap();
    }
    std::fs::write(ws.join("Cargo.toml"), "[workspace]\nmembers = [\"bad\", \"good\"]\n").unwrap();
    let run = |extra: &[&str]| {
        let mut args = vec!["build", "-j", "1", "--offline", "--color", "never"];
        args.extend_from_slice(extra);
        Command::new(env!("CARGO_BIN_EXE_rb"))
            .args(&args)
            .current_dir(&ws)
            .env("RB_HOME", root.join("home"))
            .env("RB_STORE_DIR", root.join("store"))
            .env("RB_COMPACT", "off")
            .env_remove("RUSTC_WRAPPER")
            .output()
            .unwrap()
    };
    let stopped = run(&[]);
    let stopped_text = format!(
        "{}{}",
        String::from_utf8_lossy(&stopped.stdout),
        String::from_utf8_lossy(&stopped.stderr)
    );
    assert!(!stopped.status.success(), "{stopped_text}");
    assert!(
        !stopped_text.contains("good"),
        "build aborted but still compiled the other package:\n{stopped_text}"
    );
    let kept = run(&["--keep-going"]);
    let kept_text = format!("{}{}", String::from_utf8_lossy(&kept.stdout), String::from_utf8_lossy(&kept.stderr));
    assert!(!kept.status.success(), "{kept_text}");
    assert!(kept_text.contains("good"), "independent package was not built:\n{kept_text}");
}

#[test]
fn rustdoc_deny_missing_docs_fails() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"docs\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(root.join("src/lib.rs"), "pub fn undocumented() {}\n").unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["rustdoc", "--offline", "--color", "never", "--", "-D", "missing_docs"])
        .current_dir(&root)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(!out.status.success(), "{text}");
    assert!(text.contains("missing"), "{text}");
}

#[test]
fn timings_writes_html_report() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"timed\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(root.join("src/lib.rs"), "pub fn t() {}\n").unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["build", "--timings", "--offline", "--color", "never"])
        .current_dir(&root)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    let report = root.join("target/cargo-timings/cargo-timings.html");
    let html = std::fs::read_to_string(&report).unwrap_or_else(|e| panic!("{e}\n{text}"));
    assert!(html.contains("timed") && html.contains("Build timings"), "{html}");
}

#[test]
fn package_lists_and_writes_a_crate() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"packme\"\nversion = \"0.2.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(root.join("src/lib.rs"), "pub fn ready() {}\n").unwrap();
    let listed = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["package", "--list", "--offline", "--color", "never"])
        .current_dir(&root)
        .env("RB_HOME", root.join("home"))
        .output()
        .unwrap();
    let list = String::from_utf8_lossy(&listed.stdout);
    assert!(listed.status.success(), "{}", String::from_utf8_lossy(&listed.stderr));
    assert!(list.contains("Cargo.toml") && list.contains("src/lib.rs"), "{list}");
    std::fs::write(root.join("skip.txt"), "nope\n").unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"packme\"\nversion = \"0.2.0\"\nedition = \"2021\"\nexclude = [\"skip.txt\"]\n",
    )
    .unwrap();
    let listed = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["package", "--list", "--offline", "--color", "never"])
        .current_dir(&root)
        .env("RB_HOME", root.join("home"))
        .output()
        .unwrap();
    let list = String::from_utf8_lossy(&listed.stdout);
    assert!(
        listed.status.success() && !list.contains("skip.txt") && list.contains("Cargo.toml"),
        "{list}"
    );
    let packed = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["package", "--no-verify", "--offline", "--color", "never"])
        .current_dir(&root)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&packed.stdout),
        String::from_utf8_lossy(&packed.stderr)
    );
    assert!(packed.status.success(), "{text}");
    assert!(root.join("target/package/packme-0.2.0.crate").is_file(), "{text}");
}

#[test]
fn new_package_matches_cargo_template() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["new", "--vcs", "none", "--color", "never"])
        .arg(root.join("demo"))
        .env("RB_HOME", root.join("home"))
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    let manifest = std::fs::read_to_string(root.join("demo/Cargo.toml")).unwrap();
    assert!(manifest.contains("name = \"demo\""), "{manifest}");
    assert!(manifest.contains("edition = \"2024\""), "{manifest}");
    let main = std::fs::read_to_string(root.join("demo/src/main.rs")).unwrap();
    assert!(main.contains("Hello, world!"), "{main}");
    let built = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["build", "--offline", "--color", "never"])
        .current_dir(root.join("demo"))
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let built_text = format!(
        "{}{}",
        String::from_utf8_lossy(&built.stdout),
        String::from_utf8_lossy(&built.stderr)
    );
    assert!(built.status.success(), "{built_text}");
}

#[test]
fn rustc_extra_cfg_reaches_the_crate() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"cfgd\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/lib.rs"),
        "#[cfg(rb_test_cfg)]\npub fn marked() {}\n#[cfg(not(rb_test_cfg))]\ncompile_error!(\"missing cfg\");\n",
    )
    .unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["rustc", "--offline", "--color", "never", "--", "--cfg", "rb_test_cfg"])
        .current_dir(&root)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTFLAGS")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
}

#[test]
fn read_manifest_matches_cargo_name() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let manifest = root.join("ws/Cargo.toml");
    let cargo = Command::new("cargo")
        .args(["read-manifest", "--offline", "--manifest-path"])
        .arg(&manifest)
        .output()
        .unwrap();
    let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["read-manifest", "--offline", "--manifest-path"])
        .arg(&manifest)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    assert!(cargo.status.success(), "{}", String::from_utf8_lossy(&cargo.stderr));
    assert!(rb.status.success(), "{}", String::from_utf8_lossy(&rb.stderr));
    let c: serde_json::Value = serde_json::from_slice(&cargo.stdout).unwrap();
    let r: serde_json::Value = serde_json::from_slice(&rb.stdout).unwrap();
    assert_eq!(r["name"], c["name"]);
    assert_eq!(r["version"], c["version"]);
    assert_eq!(r["targets"][0]["name"], c["targets"][0]["name"]);
}

#[test]
fn vendor_prints_the_source_replacement() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["vendor", "--offline", "--color", "never"])
        .current_dir(root.join("ws"))
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    assert!(!out.stdout.is_empty() || text.contains("replace-with"), "{text}");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("replace-with = \"vendored-sources\""), "{stdout}");
    assert!(stdout.contains("directory = \"vendor\""), "{stdout}");
    assert!(root.join("ws/vendor").is_dir());
}

#[test]
fn locate_project_matches_cargo() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let ws = root.join("ws");
    let cargo = Command::new("cargo")
        .args(["locate-project", "--message-format", "plain"])
        .current_dir(&ws)
        .output()
        .unwrap();
    let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["locate-project", "--message-format", "plain", "--color", "never"])
        .current_dir(&ws)
        .env("RB_HOME", root.join("home"))
        .output()
        .unwrap();
    let cargo_path = String::from_utf8_lossy(&cargo.stdout).trim().to_owned();
    let rb_path = String::from_utf8_lossy(&rb.stdout).trim().to_owned();
    assert!(
        cargo.status.success() && rb.status.success(),
        "{rb_path}\n{}",
        String::from_utf8_lossy(&rb.stderr)
    );
    assert_eq!(
        std::fs::canonicalize(&rb_path).unwrap(),
        std::fs::canonicalize(&cargo_path).unwrap()
    );
}

#[test]
fn install_git_copies_the_binary() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let repo = root.join("repo");
    std::fs::create_dir_all(repo.join("src")).unwrap();
    std::fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"hi\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(repo.join("src/main.rs"), "fn main() {}\n").unwrap();
    let git = |args: &[&str]| {
        let out = Command::new("git")
            .args(args)
            .current_dir(&repo)
            .env("GIT_AUTHOR_NAME", "rb")
            .env("GIT_AUTHOR_EMAIL", "rb@example.com")
            .env("GIT_COMMITTER_NAME", "rb")
            .env("GIT_COMMITTER_EMAIL", "rb@example.com")
            .env("GIT_CONFIG_GLOBAL", "/dev/null")
            .env("GIT_CONFIG_SYSTEM", "/dev/null")
            .env("GIT_CONFIG_NOSYSTEM", "1")
            .output()
            .unwrap();
        assert!(out.status.success(), "{args:?}\n{}", String::from_utf8_lossy(&out.stderr));
    };
    git(&["init", "-q", "-b", "main"]);
    git(&["add", "."]);
    git(&["-c", "commit.gpgsign=false", "commit", "-q", "-m", "init"]);
    let prefix = root.join("prefix");
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["install", "--git"])
        .arg(&repo)
        .arg("--root")
        .arg(&prefix)
        .args(["--color", "never"])
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    assert!(prefix.join("bin/hi").is_file(), "{text}");
}

#[test]
fn install_path_copies_the_binary() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let prefix = root.join("prefix");
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["install", "--path", "ws", "--offline", "--root"])
        .arg(&prefix)
        .args(["--color", "never"])
        .current_dir(&root)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    let bin = prefix.join("bin/hello-world");
    assert!(bin.is_file(), "{text}");
    let listed = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["install", "--list", "--root"])
        .arg(&prefix)
        .args(["--color", "never"])
        .env("RB_HOME", root.join("home"))
        .output()
        .unwrap();
    let list = format!(
        "{}{}",
        String::from_utf8_lossy(&listed.stdout),
        String::from_utf8_lossy(&listed.stderr)
    );
    assert!(listed.status.success() && list.contains("hello"), "{list}");
    let removed = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["uninstall", "hello", "--root"])
        .arg(&prefix)
        .args(["--color", "never"])
        .env("RB_HOME", root.join("home"))
        .output()
        .unwrap();
    let removed_text = format!(
        "{}{}",
        String::from_utf8_lossy(&removed.stdout),
        String::from_utf8_lossy(&removed.stderr)
    );
    assert!(removed.status.success(), "{removed_text}");
    assert!(!bin.exists(), "{removed_text}");
}

#[test]
fn remove_deletes_a_path_dependency() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::create_dir_all(root.join("lib/src")).unwrap();
    std::fs::write(
        root.join("lib/Cargo.toml"),
        "[package]\nname = \"mylib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(root.join("lib/src/lib.rs"), "\n").unwrap();
    std::fs::write(app.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nmylib = { path = \"../lib\" }\n",
    )
    .unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["remove", "mylib", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    let manifest = std::fs::read_to_string(app.join("Cargo.toml")).unwrap();
    assert!(!manifest.contains("mylib"), "{manifest}");
}

#[test]
fn add_path_dependency_updates_manifest_and_lock() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    let lib = root.join("lib");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::create_dir_all(lib.join("src")).unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(app.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(
        lib.join("Cargo.toml"),
        "[package]\nname = \"mylib\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(lib.join("src/lib.rs"), "\n").unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["add", "--path", "../lib", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    let manifest = std::fs::read_to_string(app.join("Cargo.toml")).unwrap();
    assert!(manifest.contains("mylib") && manifest.contains("../lib"), "{manifest}");
    let lock = std::fs::read_to_string(app.join("Cargo.lock")).unwrap();
    assert!(lock.contains("name = \"mylib\""), "{lock}");
}

#[test]
fn update_writes_a_lockfile_offline() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["update", "--offline", "--color", "never"])
        .current_dir(root.join("ws"))
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let text = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    assert!(out.status.success(), "{text}");
    let lock = std::fs::read_to_string(root.join("ws/Cargo.lock")).unwrap();
    assert!(lock.contains("name = \"hello\""), "{lock}");
    let dry = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["update", "-p", "missing-crate", "--offline", "--dry-run", "--color", "never"])
        .current_dir(root.join("ws"))
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .output()
        .unwrap();
    assert!(!dry.status.success(), "unknown spec should fail");
}

#[test]
fn message_format_json_matches_cargo_events() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/compat/fixtures/hello");
    copy_dir(&fixture, &root.join("ws"));
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["build", "--message-format=json", "--color", "never", "--offline"])
        .current_dir(root.join("ws"))
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let stdout = String::from_utf8_lossy(&out.stdout);
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(out.status.success(), "{stderr}\n{stdout}");
    assert!(!stderr.contains("Compiling"), "json format still printed human status:\n{stderr}");
    let mut artifacts = 0;
    let mut finished = false;
    for line in stdout.lines() {
        let v: serde_json::Value = serde_json::from_str(line).unwrap_or_else(|e| panic!("{e}: {line}"));
        match v["reason"].as_str() {
            Some("compiler-artifact") => {
                artifacts += 1;
                if v["target"]["name"] == "hello-world" {
                    assert!(v["executable"].as_str().unwrap_or("").ends_with("hello-world"));
                    assert_eq!(v["target"]["kind"][0], "bin");
                }
            }
            Some("build-finished") => {
                assert_eq!(v["success"], true);
                finished = true;
            }
            Some("compiler-message") => {}
            other => panic!("unexpected reason {other:?} in {line}"),
        }
    }
    assert!(artifacts >= 1, "{stdout}");
    assert!(finished, "{stdout}");
}

#[test]
fn test_runs_unit_integration_and_doc_tests() {
    let p = Project::testing();
    let log = p.ok(&["test"]);
    for expected in [
        "Running unittests src/lib.rs",
        "test tests::overflows - should panic ... ok",
        "test tests::slow ... ignored",
        "Running unittests src/main.rs",
        "Running tests/cli.rs",
        "test runs_the_binary ... ok",
        "test has_a_scratch_dir ... ok",
        "test runs_in_the_package_root ... ok",
        "Doc-tests tf",
        "test tf/src/lib.rs - add (line 12) - compile fail ... ok",
        "Doc-tests tf_macros",
        "test tf-macros/src/lib.rs - answer (line 5) ... ok",
    ] {
        assert!(log.contains(expected), "missing `{expected}` in:\n{log}");
    }
    // `needs-extra` requires a feature that is off
    assert!(!log.contains("needs-extra"), "{log}");

    let log = p.ok(&["test", "--features", "tf/extra", "--test", "needs-extra"]);
    assert!(log.contains("test only_with_extra ... ok"), "{log}");
    assert!(!log.contains("Doc-tests"), "an explicit target filter skips doctests:\n{log}");

    let log = p.ok(&["test", "-p", "tf", "--lib", "overflows"]);
    assert!(log.contains("1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out"), "{log}");

    let log = p.ok(&["test", "--no-run"]);
    assert!(log.contains("Executable tests/cli.rs"), "{log}");
    assert!(!log.contains("test result"), "{log}");
}

#[test]
fn cached_tests_still_find_their_binaries() {
    let p = Project::testing();
    p.ok(&["test", "-p", "tf", "--test", "cli"]);
    std::fs::remove_dir_all(p.ws().join("target")).unwrap();
    let log = p.ok(&["test", "-p", "tf", "--test", "cli"]);
    assert!(log.contains("(0 compiled"), "everything comes from the store:\n{log}");
    assert!(log.contains("test runs_the_binary ... ok"), "{log}");
    // cargo's layout: the binary is uplifted and the test runs from `target/debug/deps/`
    let exe = if cfg!(windows) { "tf.exe" } else { "tf" };
    assert!(p.ws().join("target/debug").join(exe).is_file());
    assert!(log.contains("Running tests/cli.rs (target/debug/deps/cli-"), "{log}");
}

fn write(path: &Path, text: &str) {
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, text).unwrap();
}

/// Found on a Tauri app: resolver 2 comes from an inherited edition, `dep/feat` on a dependency
/// for another platform enables nothing, and a custom `build` file names the build script
#[test]
fn resolver_and_build_script_follow_cargo() {
    let dir = tempfile::tempdir().unwrap();
    let ws = dir.path().canonicalize().unwrap();
    write(
        &ws.join("Cargo.toml"),
        r#"[workspace]
members = ["wasm-only"]

[workspace.package]
edition = "2021"

[package]
name = "app"
version = "0.1.0"
edition.workspace = true
build = "gen.rs"

[features]
default = ["sleep"]
sleep = ["wasm-only/timers"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-only = { path = "wasm-only", optional = true }
"#,
    );
    write(&ws.join("gen.rs"), "fn main() {}\n");
    write(&ws.join("src/main.rs"), "fn main() {}\n");
    write(
        &ws.join("wasm-only/Cargo.toml"),
        "[package]\nname = \"wasm-only\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[features]\ntimers = []\n",
    );
    write(&ws.join("wasm-only/src/lib.rs"), "");
    let out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["build", "--unit-graph"])
        .current_dir(&ws)
        .env("RB_STORE_DIR", ws.join("store"))
        .env("RB_HOME", ws.join("home"))
        .output()
        .unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let graph: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let units = graph["units"].as_array().unwrap();
    let app = units.iter().find(|u| u["target"]["name"] == "app").unwrap();
    assert_eq!(
        app["features"],
        serde_json::json!(["default", "sleep"]),
        "no implicit `wasm-only` feature"
    );
    assert!(
        !units.iter().any(|u| u["pkg_id"].as_str().unwrap().contains("wasm-only")),
        "not built for this platform"
    );
    assert!(units.iter().any(|u| u["target"]["name"] == "build-script-gen"));
}

/// `-C metadata` of the `tf` library in a verbose build log
fn tf_metadata(log: &str) -> String {
    let line = log
        .lines()
        .find(|l| l.contains("--crate-name tf ") && l.contains("--crate-type lib"))
        .unwrap_or_else(|| panic!("tf was not compiled:\n{log}"));
    line.split("metadata=")
        .nth(1)
        .unwrap()
        .split(['\'', ' '])
        .next()
        .unwrap()
        .to_owned()
}

#[test]
fn edits_keep_crate_identity_for_incremental_compilation() {
    let p = Project::testing();
    let before = tf_metadata(&p.ok(&["build", "-v", "-p", "tf"]));
    let lib = p.ws().join("tf/src/lib.rs");
    let src = std::fs::read_to_string(&lib).unwrap();
    std::fs::write(&lib, src.replace("a + b", "a.wrapping_add(b).wrapping_add(0)")).unwrap();
    let after = tf_metadata(&p.ok(&["build", "-v", "-p", "tf"]));
    assert_eq!(before, after, "rustc's incremental cache is keyed by -C metadata");
    let sessions = std::fs::read_dir(p.ws().join("target/rb/debug/host/incremental"))
        .unwrap()
        .filter(|e| e.as_ref().unwrap().file_name().to_string_lossy().starts_with("tf-"))
        .count();
    assert_eq!(
        sessions, 2,
        "one incremental directory each for the tf lib and bin, reused across the edit"
    );

    // The binary reflects the edit, and reverting restores the previous version from the store
    let out = p.rb(&["run", "-q", "-p", "tf"]);
    assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "3");
    std::fs::write(&lib, &src).unwrap();
    let log = p.ok(&["build", "-p", "tf"]);
    assert!(log.contains("(0 compiled"), "{log}");
}

#[test]
fn test_failures_are_reported() {
    let p = Project::testing();
    let lib = p.ws().join("tf/src/lib.rs");
    let src = std::fs::read_to_string(&lib).unwrap();
    std::fs::write(
        &lib,
        src.replace("assert_eq!(super::add(1, 2), 3);", "assert_eq!(super::add(1, 2), 4);"),
    )
    .unwrap();

    let out = p.rb(&["test", "-p", "tf"]);
    let log = String::from_utf8_lossy(&out.stderr).into_owned() + &String::from_utf8_lossy(&out.stdout);
    assert!(!out.status.success());
    assert!(log.contains("test failed, to rerun pass `-p tf --lib`"), "{log}");
    assert!(!log.contains("Running tests/cli.rs"), "stops at the first failure:\n{log}");

    let out = p.rb(&["test", "-p", "tf", "--no-fail-fast"]);
    let log = String::from_utf8_lossy(&out.stderr).into_owned() + &String::from_utf8_lossy(&out.stdout);
    assert!(!out.status.success());
    assert!(
        log.contains("Running tests/cli.rs") && log.contains("Doc-tests tf"),
        "keeps going:\n{log}"
    );
    assert!(log.contains("1 target failed:"), "{log}");
}

#[test]
fn run_passes_arguments_and_exit_codes() {
    let p = Project::testing();
    let out = p.rb(&["run", "-q", "-p", "tf", "--", "a", "b"]);
    assert!(out.status.success());
    assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "args: a b");

    let out = p.rb(&["run", "-q", "-p", "tf", "--example", "demo"]);
    assert_eq!(String::from_utf8_lossy(&out.stdout).trim(), "demo 42");
    assert!(p.ws().join("target/debug/examples/demo").exists() || p.ws().join("target/debug/examples/demo.exe").exists());

    std::fs::write(p.ws().join("tf/examples/exit7.rs"), "fn main() { std::process::exit(7) }").unwrap();
    assert_eq!(p.rb(&["run", "-q", "-p", "tf", "--example", "exit7"]).status.code(), Some(7));

    let out = p.rb(&["run"]);
    assert!(!out.status.success(), "two packages: `rb run` needs -p");
}

#[test]
fn bench_passes_bench_flag() {
    let p = Project::testing();
    let log = p.ok(&["bench"]);
    assert!(log.contains("`bench` profile [optimized]"), "{log}");
    assert!(log.contains("speed: sum=500500 bench-mode=true"), "{log}");
    // Unit tests run in bench mode: they are listed as ignored, not executed
    assert!(log.contains("test tests::adds ... ignored"), "{log}");
}

fn nightly_rustc() -> Option<PathBuf> {
    let out = Command::new("rustup")
        .args(["which", "--toolchain", "nightly", "rustc"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let path = PathBuf::from(String::from_utf8(out.stdout).ok()?.trim());
    path.is_file().then_some(path)
}

#[test]
fn json_target_spec_matches_cargo() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::write(app.join("custom-target.json"), "{}\n").unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(app.join("src/lib.rs"), "#![feature(no_core)]\n#![no_core]\n#![no_std]\n").unwrap();
    let rb = |args: &[&str]| {
        Command::new(env!("CARGO_BIN_EXE_rb"))
            .args(args)
            .current_dir(&app)
            .env("RB_HOME", root.join("home"))
            .env("RB_STORE_DIR", root.join("store"))
            .env("RB_COMPACT", "off")
            .env("CARGO_TERM_COLOR", "never")
            .env_remove("RUSTC_WRAPPER")
            .output()
            .unwrap()
    };
    let missing_flag = rb(&["build", "--target", "custom-target.json", "--offline", "--color", "never"]);
    let err = String::from_utf8_lossy(&missing_flag.stderr);
    assert!(!missing_flag.status.success());
    assert!(err.contains("`.json` target specs require -Zjson-target-spec"), "{err}");
    let missing_file = rb(&[
        "build",
        "-Zjson-target-spec",
        "--target",
        "missing.json",
        "--offline",
        "--color",
        "never",
    ]);
    let err = String::from_utf8_lossy(&missing_file.stderr);
    assert!(!missing_file.status.success());
    assert!(err.contains("target path `missing.json` is not a valid file"), "{err}");
    let unknown = rb(&["build", "-Zno-such-flag", "--offline", "--color", "never"]);
    assert!(String::from_utf8_lossy(&unknown.stderr).contains("unknown `-Z` flag specified: no-such-flag"));

    let Some(nightly) = nightly_rustc() else { return };
    let spec = Command::new(&nightly)
        .args(["-Z", "unstable-options", "--print", "target-spec-json"])
        .output()
        .unwrap();
    assert!(spec.status.success(), "{}", String::from_utf8_lossy(&spec.stderr));
    let mut spec_json: serde_json::Value = serde_json::from_slice(&spec.stdout).unwrap();
    spec_json.as_object_mut().unwrap().remove("metadata");
    std::fs::write(app.join("custom-target.json"), serde_json::to_vec_pretty(&spec_json).unwrap()).unwrap();
    std::fs::create_dir_all(app.join(".cargo")).unwrap();
    std::fs::write(
        app.join(".cargo/config.toml"),
        "[target.custom-target]\nrustflags = [\"--cfg\", \"rb_json_spec\"]\n",
    )
    .unwrap();
    std::fs::write(
        app.join("build.rs"),
        "fn main() {\n    let out = std::path::Path::new(&std::env::var(\"OUT_DIR\").unwrap()).join(\"target.txt\");\n    std::fs::write(out, std::env::var(\"TARGET\").unwrap()).unwrap();\n}\n",
    )
    .unwrap();
    let cargo = Command::new("cargo")
        .args([
            "+nightly",
            "build",
            "-Zjson-target-spec",
            "--target",
            "custom-target.json",
            "--offline",
            "-v",
            "--color",
            "never",
        ])
        .current_dir(&app)
        .env("RUSTUP_TOOLCHAIN", "nightly")
        .output()
        .unwrap();
    let cargo_err = String::from_utf8_lossy(&cargo.stderr);
    assert!(cargo.status.success(), "{cargo_err}");
    let rb_out = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args([
            "build",
            "-Zjson-target-spec",
            "--target",
            "custom-target.json",
            "--offline",
            "-v",
            "--color",
            "never",
        ])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env("RUSTC", &nightly)
        .env_remove("RUSTC_WRAPPER")
        .env_remove("RUSTUP_TOOLCHAIN")
        .output()
        .unwrap();
    let rb_err = String::from_utf8_lossy(&rb_out.stderr);
    assert!(rb_out.status.success(), "{rb_err}");
    assert!(app.join("target/custom-target/debug/libapp.rlib").is_file());
    let mut recorded = Vec::new();
    let mut stack = vec![app.join("target")];
    while let Some(dir) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&dir) else { continue };
        for entry in rd.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if entry.file_name() == "target.txt" {
                recorded.push(std::fs::read_to_string(&path).unwrap());
            }
        }
    }
    assert!(recorded.len() >= 2, "cargo and rb should each record TARGET, got {recorded:?}");
    assert!(recorded.iter().all(|t| t.trim() == "custom-target"), "{recorded:?}");
    for log in [cargo_err.as_ref(), rb_err.as_ref()] {
        assert!(log.contains("custom-target.json"), "{log}");
        assert!(log.contains("-Zunstable-options"), "{log}");
        assert!(log.contains("--cfg") && log.contains("rb_json_spec"), "{log}");
    }
}

#[test]
fn doc_documents_workspace_and_skips_bin_named_like_lib() {
    let p = Project::testing();
    let log = p.ok(&["doc"]);
    assert!(log.contains("Generated") && log.contains("and 1 other file"), "{log}");
    let doc = p.ws().join("target/doc");
    assert!(doc.join("tf/index.html").is_file());
    assert!(doc.join("tf_macros/index.html").is_file());
    assert!(
        !doc.join("tf/fn.main.html").exists(),
        "the `tf` bin must not overwrite the `tf` lib docs"
    );
}

#[test]
fn git_index_registry_matches_cargo() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let script = r#"
import os, tarfile, hashlib, json, subprocess, pathlib
root = pathlib.Path(os.environ["ROOT"])
index, dl, app = root / "index", root / "dl", root / "app"
(index / "de" / "mo").mkdir(parents=True)
dl.mkdir()
(app / "src").mkdir(parents=True)
(app / ".cargo").mkdir()
crate = dl / "demo-0.1.0.crate"
with tarfile.open(crate, "w:gz") as tar:
    for name, text in {
        "demo-0.1.0/Cargo.toml": '[package]\nname = "demo"\nversion = "0.1.0"\nedition = "2021"\n',
        "demo-0.1.0/src/lib.rs": "pub fn hi() -> u8 { 7 }\n",
    }.items():
        data = text.encode()
        info = tarfile.TarInfo(name)
        info.size = len(data)
        tar.addfile(info, __import__("io").BytesIO(data))
ck = hashlib.sha256(crate.read_bytes()).hexdigest()
(index / "de" / "mo" / "demo").write_text(
    json.dumps({"name":"demo","vers":"0.1.0","deps":[],"cksum":ck,"features":{},"yanked":False}) + "\n"
)
(index / "config.json").write_text(json.dumps({"dl": f"file://{dl}/{{crate}}-{{version}}.crate"}))
(app / "Cargo.toml").write_text('[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\ndemo = { version = "0.1", registry = "local" }\n')
(app / "src" / "main.rs").write_text('fn main() { println!("{}", demo::hi()); }\n')
(app / ".cargo" / "config.toml").write_text(f'[registries.local]\nindex = "file://{index}"\n')
env = {**os.environ, "GIT_AUTHOR_NAME":"rb","GIT_AUTHOR_EMAIL":"rb@example.com","GIT_COMMITTER_NAME":"rb","GIT_COMMITTER_EMAIL":"rb@example.com","GIT_CONFIG_GLOBAL":"/dev/null","GIT_CONFIG_NOSYSTEM":"1"}
def git(*args):
    subprocess.check_call(["git", "-c", "commit.gpgsign=false", *args], cwd=index, env=env)
git("init", "-q", "-b", "main")
git("add", ".")
git("commit", "-q", "-m", "index")
"#;
    let setup = Command::new("python3").arg("-c").arg(script).env("ROOT", &root).output().unwrap();
    assert!(setup.status.success(), "{}", String::from_utf8_lossy(&setup.stderr));
    let app = root.join("app");
    let cargo = Command::new("cargo")
        .args(["run", "--quiet", "--color", "never"])
        .current_dir(&app)
        .env("CARGO_HOME", root.join("cargo-home"))
        .output()
        .unwrap();
    assert!(cargo.status.success(), "{}", String::from_utf8_lossy(&cargo.stderr));
    let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["run", "--quiet", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .unwrap();
    let rb_err = String::from_utf8_lossy(&rb.stderr);
    assert!(rb.status.success(), "{rb_err}");
    assert_eq!(
        String::from_utf8_lossy(&rb.stdout).trim(),
        String::from_utf8_lossy(&cargo.stdout).trim()
    );
}

#[test]
fn build_std_core_matches_cargo() {
    let Some(nightly) = nightly_rustc() else { return };
    let src = nightly
        .ancestors()
        .nth(2)
        .unwrap()
        .join("lib/rustlib/src/rust/library/core/Cargo.toml");
    if !src.is_file() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let app = root.join("app");
    std::fs::create_dir_all(app.join("src")).unwrap();
    std::fs::write(
        app.join("Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(
        app.join("src/lib.rs"),
        "#![no_std]\npub fn n() -> usize { core::mem::size_of::<u8>() }\n",
    )
    .unwrap();
    let cargo = Command::new("cargo")
        .args(["+nightly", "build", "-Zbuild-std=core", "--color", "never"])
        .current_dir(&app)
        .env("RUSTUP_TOOLCHAIN", "nightly")
        .env("CARGO_HOME", root.join("cargo-home"))
        .output()
        .unwrap();
    assert!(cargo.status.success(), "{}", String::from_utf8_lossy(&cargo.stderr));
    let rb = Command::new(env!("CARGO_BIN_EXE_rb"))
        .args(["build", "-Zbuild-std=core", "--offline", "--color", "never"])
        .current_dir(&app)
        .env("RB_HOME", root.join("home"))
        .env("RB_STORE_DIR", root.join("store"))
        .env("RB_COMPACT", "off")
        .env("RUSTC", &nightly)
        .env_remove("RUSTC_WRAPPER")
        .env_remove("RUSTUP_TOOLCHAIN")
        .output()
        .unwrap();
    let err = String::from_utf8_lossy(&rb.stderr);
    assert!(rb.status.success(), "{err}");
    assert!(app.join("target/debug/libapp.rlib").is_file(), "{err}");
}
